language: node_js
node_js:
    - '0.12'
before_install:
    - gem update --system
    - gem install scss-lint -v 0.35.0
    - npm install -g grunt-cli
notifications:
    email:
        - info@iliakolev.com
