language: node_js
node_js:
  - "0.10"
  - "0.12"
before_install:
  - rvm use 1.9.3
install:
  - travis_retry npm install -g grunt-cli
  - travis_retry npm install
  - travis_retry gem install --no-document "sass:~>3.4.13" "scss-lint:~>0.35.0"
matrix:
  fast_finish: true
notifications:
  email: info@iliakolev.com
