language: node_js

node_js:
  - "4"

env:
  matrix:
    - RUBY_VERSION=2.2

before_install:
  - rvm install $RUBY_VERSION
  - rvm use $RUBY_VERSION --fuzzy

install:
  - travis_retry npm install -g grunt-cli
  - travis_retry npm install
  - travis_retry gem install --no-document "sass:~>3.4.13" "scss-lint:~>0.35.0"

matrix:
  fast_finish: true

notifications:
  email: info@iliakolev.com
